CREATE SCHEMA IF NOT EXISTS PANTHER_DB.RAW;
CREATE SCHEMA IF NOT EXISTS PANTHER_DB.CURATED;

CREATE FILE FORMAT IF NOT EXISTS PANTHER_DB.RAW.JSON_ARRAY_FORMAT
  TYPE = JSON
  STRIP_OUTER_ARRAY = FALSE
  COMPRESSION = AUTO;

CREATE STAGE IF NOT EXISTS PANTHER_DB.RAW.GAMMA_MARKETS_STAGE
  FILE_FORMAT = (FORMAT_NAME = PANTHER_DB.RAW.JSON_ARRAY_FORMAT);


CREATE TABLE IF NOT EXISTS PANTHER_DB.RAW.GAMMA_MARKET_PAGES_STAGE (
  source_file_name STRING NOT NULL,
  page_name STRING NOT NULL,
  page_limit NUMBER(18,0) NOT NULL,
  page_offset NUMBER(18,0) NOT NULL,
  source_is_active BOOLEAN,
  source_is_closed BOOLEAN,
  expected_row_count NUMBER(18,0),
  expected_md5_hex STRING,
  file_content_key STRING NOT NULL,
  file_last_modified TIMESTAMP_NTZ,
  payload VARIANT NOT NULL,
  staged_at TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS PANTHER_DB.RAW.GAMMA_MARKET_PAGES (
  source_file_name STRING NOT NULL,
  page_name STRING NOT NULL,
  page_limit NUMBER(18,0) NOT NULL,
  page_offset NUMBER(18,0) NOT NULL,
  source_is_active BOOLEAN,
  source_is_closed BOOLEAN,
  expected_row_count NUMBER(18,0),
  expected_md5_hex STRING,
  file_content_key STRING NOT NULL,
  file_last_modified TIMESTAMP_NTZ,
  payload VARIANT NOT NULL,
  staged_at TIMESTAMP_NTZ NOT NULL,
  raw_loaded_at TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT gamma_market_pages_uk UNIQUE (source_file_name, file_content_key)
);

CREATE TABLE IF NOT EXISTS PANTHER_DB.CURATED.GAMMA_MARKETS (
  market_id STRING NOT NULL,
  api_id STRING,
  condition_id STRING,
  question STRING,
  slug STRING,
  resolution_source STRING,
  description STRING,
  start_date TIMESTAMP_NTZ,
  end_date TIMESTAMP_NTZ,
  created_at TIMESTAMP_NTZ,
  updated_at TIMESTAMP_NTZ,
  end_date_iso STRING,
  start_date_iso STRING,
  has_reviewed_dates BOOLEAN,
  image STRING,
  icon STRING,
  active BOOLEAN,
  closed BOOLEAN,
  is_new BOOLEAN,
  archived BOOLEAN,
  featured BOOLEAN,
  restricted BOOLEAN,
  approved BOOLEAN,
  accepting_orders BOOLEAN,
  accepting_orders_timestamp TIMESTAMP_NTZ,
  ready BOOLEAN,
  funded BOOLEAN,
  enable_order_book BOOLEAN,
  automatically_active BOOLEAN,
  order_price_min_tick_size NUMBER(18,6),
  order_min_size NUMBER(18,6),
  liquidity_text STRING,
  liquidity NUMBER(38,12),
  liquidity_clob NUMBER(38,12),
  liquidity_num NUMBER(38,12),
  volume_text STRING,
  volume NUMBER(38,12),
  volume_clob NUMBER(38,12),
  volume_24hr NUMBER(38,12),
  volume_24hr_clob NUMBER(38,12),
  volume_1wk NUMBER(38,12),
  volume_1wk_clob NUMBER(38,12),
  volume_1mo NUMBER(38,12),
  volume_1mo_clob NUMBER(38,12),
  volume_1yr NUMBER(38,12),
  volume_1yr_clob NUMBER(38,12),
  volume_num NUMBER(38,12),
  best_bid NUMBER(18,6),
  best_ask NUMBER(18,6),
  last_trade_price NUMBER(18,6),
  spread NUMBER(18,6),
  one_hour_price_change NUMBER(18,6),
  one_day_price_change NUMBER(18,6),
  one_week_price_change NUMBER(18,6),
  one_month_price_change NUMBER(18,6),
  one_year_price_change NUMBER(18,6),
  rewards_min_size NUMBER(18,6),
  rewards_max_spread NUMBER(18,6),
  uma_bond NUMBER(18,6),
  uma_reward NUMBER(18,6),
  cyom BOOLEAN,
  competitive NUMBER(18,6),
  outcomes VARIANT,
  outcome_prices VARIANT,
  clob_token_ids VARIANT,
  clob_rewards VARIANT,
  events VARIANT,
  uma_resolution_statuses VARIANT,
  market_maker_address STRING,
  submitted_by STRING,
  resolved_by STRING,
  group_item_title STRING,
  group_item_threshold STRING,
  question_id STRING,
  neg_risk BOOLEAN,
  neg_risk_other BOOLEAN,
  neg_risk_market_id STRING,
  neg_risk_request_id STRING,
  custom_liveness NUMBER(18,6),
  pager_duty_notification_enabled BOOLEAN,
  fees_enabled BOOLEAN,
  fee_type STRING,
  holding_rewards_enabled BOOLEAN,
  rfq_enabled BOOLEAN,
  manual_activation BOOLEAN,
  clear_book_on_start BOOLEAN,
  show_gmp_series BOOLEAN,
  show_gmp_outcome BOOLEAN,
  series_color STRING,
  pending_deployment BOOLEAN,
  deploying BOOLEAN,
  deploying_timestamp TIMESTAMP_NTZ,
  requires_translation BOOLEAN,
  market_payload_hash STRING,
  market_payload VARIANT NOT NULL,
  source_file_name STRING NOT NULL,
  source_page_name STRING NOT NULL,
  source_page_limit NUMBER(18,0) NOT NULL,
  source_page_offset NUMBER(18,0) NOT NULL,
  raw_loaded_at TIMESTAMP_NTZ NOT NULL,
  processed_at TIMESTAMP_NTZ,
  transformed_at TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT gamma_markets_pk PRIMARY KEY (market_id)
);

ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS market_payload_hash STRING;
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS processed_at TIMESTAMP_NTZ;
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS api_id STRING;
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS end_date_iso STRING;
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS start_date_iso STRING;
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS has_reviewed_dates BOOLEAN;
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS is_new BOOLEAN;
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS automatically_active BOOLEAN;
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS liquidity_text STRING;
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS volume_text STRING;
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS liquidity_num NUMBER(38,12);
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS volume_num NUMBER(38,12);
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS volume_24hr_clob NUMBER(38,12);
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS volume_1wk_clob NUMBER(38,12);
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS volume_1mo_clob NUMBER(38,12);
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS volume_1yr_clob NUMBER(38,12);
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS rewards_min_size NUMBER(18,6);
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS rewards_max_spread NUMBER(18,6);
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS uma_bond NUMBER(18,6);
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS uma_reward NUMBER(18,6);
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS cyom BOOLEAN;
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS competitive NUMBER(18,6);
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS accepting_orders_timestamp TIMESTAMP_NTZ;
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS market_maker_address STRING;
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS submitted_by STRING;
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS resolved_by STRING;
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS group_item_title STRING;
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS group_item_threshold STRING;
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS question_id STRING;
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS neg_risk BOOLEAN;
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS neg_risk_other BOOLEAN;
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS neg_risk_market_id STRING;
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS neg_risk_request_id STRING;
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS custom_liveness NUMBER(18,6);
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS pager_duty_notification_enabled BOOLEAN;
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS fees_enabled BOOLEAN;
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS fee_type STRING;
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS holding_rewards_enabled BOOLEAN;
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS rfq_enabled BOOLEAN;
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS manual_activation BOOLEAN;
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS clear_book_on_start BOOLEAN;
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS show_gmp_series BOOLEAN;
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS show_gmp_outcome BOOLEAN;
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS series_color STRING;
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS pending_deployment BOOLEAN;
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS deploying BOOLEAN;
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS deploying_timestamp TIMESTAMP_NTZ;
ALTER TABLE PANTHER_DB.CURATED.GAMMA_MARKETS
  ADD COLUMN IF NOT EXISTS requires_translation BOOLEAN;
